services:
  drupal:
    image: drupal:10.0.8
    ports:
      - "8080:80"
    networks:
      - halnetwork
    volumes:
      - type: volume
        source: drupal-modules
        target: /var/www/html/modules
      - type: volume
        source: drupal-profiles
        target: /var/www/html/profiles
      - type: volume
        source: drupal-sites
        target: /var/www/html/sites
      - type: volume
        source: drupal-themes
        target: /var/www/html/themes
  postgres:
    image: postgres:15.2
    environment:
      - POSTGRES_DB=drupal
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    networks:
      - halnetwork

networks:
   halnetwork:

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
